name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Кэширование зависимостей venv и системных пакетов Buildozer
      - name: Cache Buildozer and Venv
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            .buildozer
            .venv
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      # Установка системных зависимостей, необходимых для сборки Android на Ubuntu
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache git libffi-dev libssl-dev autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake zip unzip openjdk-17-jdk

      # Создание виртуального окружения и установка buildozer/cython
      - name: Create Virtual Environment and Install Dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install buildozer cython setuptools

      # Запуск сборки внутри активированного виртуального окружения
      - name: Build with Buildozer
        run: |
          source .venv/bin/activate
          buildozer -v android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk

